apiVersion: apps/v1
kind: Deployment
metadata:
  name: cu-final
  labels:
    run: cu-final
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: cu-final
  template:
    metadata:
      labels:
        app: cu-final
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: cu-acr-pass
      containers:
        - name: cu-final
          image: bennyau.azurecr.io/cu-final:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"
          env:
          - name: DATABASE_SERVICE_HOST
            value: mssql-server-linux
          - name: MSSQL_DATABASE
            value: mydatabase
          - name: MSSQL_USER
            value: sa
          - name: MSSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql-pass
                key: SA_PASSWORD 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cu-final
  name: cu-final
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: cu-final
  type: LoadBalancer