apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql-server-linux
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql-server-linux
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: >-
                Y
        - name: SA_PASSWORD
          value: >-
                StrongPassw0rd
        volumeMounts:
        - name: mssql-server-linux
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-server-linux
        persistentVolumeClaim:
          claimName: azure-managed-disk

