kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium #AKS has this storage class build in
  resources:
    requests:
      storage: 8Gi