#!/bin/bash
DATABASE_SERVICE_HOST=127.0.0.1
export DATABASE_SERVICE_HOST
MSSQL_DATABASE=mydatabase
export MSSQL_DATABASE
MSSQL_USER=sa
export MSSQL_USER
MSSQL_PASSWORD="StrongPassw0rd"
export MSSQL_PASSWORD
echo "DATABASE_SERVICE_HOST=${DATABASE_SERVICE_HOST}"
echo "MSSQL_DATABASE=${MSSQL_DATABASE}"
echo "MSSQL_USER=${MSSQL_USER}"
echo "MSSQL_PASSWORD=${MSSQL_PASSWORD}"
#echo SqlServer.sql
#cat SqlServer.sql
